# ./Dockerfile

FROM elixir:latest

RUN mkdir /app

COPY . /app

WORKDIR /app

EXPOSE 4000

RUN apt-get update
RUN apt-get install -y postgresql-client
RUN apt-get install -y inotify-tools
RUN apt-get install -y nodejs
RUN mix local.hex --force
RUN mix archive.install hex phx_new --force
RUN mix local.rebar --force

RUN  apt-get install -y dos2unix

RUN dos2unix /app/entrypoint.sh

RUN mix deps.get

RUN mix do compile, release

RUN chmod +x entrypoint.sh

CMD ["/app/entrypoint.sh"]